# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: David Antona
title: Technical Lead
email: antonagnu@gmail.co.uk
website: https://2sherpas.github.io/

# Social links
#twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: david-antona-8b938376
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's David and I'm a senior Technical Lead as well as a book worm and a long distance runner. 
  
  I have worked at a number of companies  with many different roles, from installing phone cable to software development and now leading technicals teams.
  
  This combination of roles and companies has provided me with a wide set of skills that helps me participate in different areas of any project. and leadership skills.
  
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering and leadong people some of my other interests and hobbies are:
   - Running
   - Rock climbing
   - Reading
   - Cooking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
